@baseUrl = http://localhost:3333

###
POST {{baseUrl}}/users
Content-Type: application/json

{
  "first_name": "Lucas",
  "last_name": "Gomes",
  "user_name": "lucasgomes",
  "email": "lucas.pfgomes@gmail.com",
  "password": "123456789"
}

###
GET {{baseUrl}}/users

###
PATCH {{baseUrl}}/users/760741e1-01b2-4890-91a8-fff6902429d4
Content-Type: application/json

{
  "first_name": "LucasE",
}

###
DELETE {{baseUrl}}/users/760741e1-01b2-4890-91a8-fff6902429d4
